version: '3'
networks:
  frontend:
    driver: bridge
  database:
    driver: bridge
services:
  nginx:
    build:
      context: .
      dockerfile: ./dockers/nginx.dockerfile
      args:
        udcpoption: ${UDCP_OPTION}
    environment:
      UDCP_NAME: ${UDCP_NAME}
      UDPC_PORT: ${UDCP_OPTION}
    volumes:
      - ./local_shares/keys:/ssl_certs
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
      - 8443:8443
    depends_on:
      - cwl
      - taxonomy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 120s
  cwl:
    build:
      context: .
      dockerfile: ./dockers/cwl.dockerfile
      args:
        udcpoption: ${UDCP_OPTION}
    environment:
      UDCP_NAME: ${UDCP_NAME}
      UDPC_PORT: ${UDCP_OPTION}
      LEAP_CLI: /usr/app/OUTPUT/
    depends_on:
      - mongo
    volumes:
      - ./local_shares/blob/CWL:/usr/app/blob-local-storage
      - ./local_shares/token_keys:/webgme_token_keys
    networks:
      - database
      - frontend
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        window: 240s
  taxonomy:
    build:
      context: .
      dockerfile: ./dockers/taxonomy.dockerfile
      args:
        udcpoption: ${UDCP_OPTION}
    environment:
      UDCP_NAME: ${UDCP_NAME}
      UDPC_PORT: ${UDCP_OPTION}
    depends_on:
      - mongo
    volumes:
      - ./local_shares/blob/Taxonomy:/webgme-taxonomy/blob-local-storage
      - ./local_shares/token_keys:/webgme_token_keys
    networks:
      - database
      - frontend
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        window: 240s
      resources:
        limits:
          memory: "1g"
  mongo:
    image: mongo:5.0.18
    volumes:
      - ./local_shares/db:/data/db
    networks:
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 120s
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph
    volumes:
      - ./local_shares/jvm-11.options:/opt/janusgraph/conf/jvm-11.options
    networks:
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 120s
